#!/bin/sh

hostname="$1"
config=$HOME/config

ssh $hostname "mkdir -p .config"

scp -r $config/ack   $hostname:.config/
scp -r $config/emacs $hostname:.config/
scp -r $config/git   $hostname:.config/

scp $config/zsh/env  $hostname:.zshenv
scp $config/zsh/rc   $hostname:.zshrc
