#!/bin/sh
# https://stackoverflow.com/questions/149057/how-to-remove-trailing-whitespace-of-all-files-recursively/10120431#10120431
git grep -I --name-only -z -e '' | xargs -0 sed -i 's/[ \t]\+\(\r\?\)$/\1/'
